[package]
name = "rm-unused-img"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
iced_graphics = { version = "0.8.0", features = ["font-source"] }
rfd = "0.11.4"
regex = "1.8.1"

